2021-12-04 03:50:42,717 INFO    MainThread:343929 [wandb_setup.py:_flush():71] setting env: {}
2021-12-04 03:50:42,717 INFO    MainThread:343929 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-04 03:50:42,717 INFO    MainThread:343929 [wandb_init.py:_log_setup():371] Logging user logs to /media/avidbeam/workspace/Abdelrahman_Workspace/Project_Codes/Synergy/wandb/run-20211204_035042-3rzh9b42/logs/debug.log
2021-12-04 03:50:42,717 INFO    MainThread:343929 [wandb_init.py:_log_setup():372] Logging internal logs to /media/avidbeam/workspace/Abdelrahman_Workspace/Project_Codes/Synergy/wandb/run-20211204_035042-3rzh9b42/logs/debug-internal.log
2021-12-04 03:50:42,717 INFO    MainThread:343929 [wandb_init.py:init():404] calling init triggers
2021-12-04 03:50:42,717 INFO    MainThread:343929 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-04 03:50:42,717 INFO    MainThread:343929 [wandb_init.py:init():449] starting backend
2021-12-04 03:50:42,717 INFO    MainThread:343929 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-04 03:50:42,734 INFO    MainThread:343929 [backend.py:ensure_launched():199] starting backend process...
2021-12-04 03:50:42,748 INFO    MainThread:343929 [backend.py:ensure_launched():204] started backend process with pid: 344037
2021-12-04 03:50:42,749 INFO    MainThread:343929 [wandb_init.py:init():458] backend started and connected
2021-12-04 03:50:42,750 INFO    MainThread:343929 [wandb_init.py:init():519] updated telemetry
2021-12-04 03:50:42,789 INFO    MainThread:343929 [wandb_init.py:init():549] communicating current version
2021-12-04 03:50:43,347 INFO    MainThread:343929 [wandb_init.py:init():554] got version response 
2021-12-04 03:50:43,347 INFO    MainThread:343929 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-04 03:50:44,066 INFO    MainThread:343929 [wandb_init.py:init():587] run resumed
2021-12-04 03:50:44,071 INFO    MainThread:343929 [wandb_init.py:init():592] starting run threads in backend
2021-12-04 03:50:44,771 INFO    MainThread:343929 [wandb_run.py:_console_start():1816] atexit reg
2021-12-04 03:50:44,771 INFO    MainThread:343929 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-12-04 03:50:44,771 INFO    MainThread:343929 [wandb_run.py:_redirect():1695] Redirecting console.
2021-12-04 03:50:44,772 INFO    MainThread:343929 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-04 03:50:44,772 INFO    MainThread:343929 [wandb_init.py:init():619] run started, returning control to user process
2021-12-04 03:51:58,571 INFO    MainThread:343929 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 255
2021-12-04 03:51:58,571 INFO    MainThread:343929 [wandb_run.py:_restore():1758] restore
2021-12-04 03:52:01,090 INFO    MainThread:343929 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1423
  total_bytes: 1423
}

2021-12-04 03:52:06,192 INFO    MainThread:343929 [wandb_run.py:_wait_for_finish():1916] got exit ret: None
2021-12-04 03:52:06,293 INFO    MainThread:343929 [wandb_run.py:_restore():1758] restore
